# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Gianluca Pacchiella"
tagline:          'I code for food'
description:      'I code for food'
baseurl:          '/yadb'

author:
  name:           'Gianluca Pacchiella'
  url:            https://ktln2.org

paginate:         5
exclude:          ['extras/',]