# Dependencies
pygments:         true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]

# Permalinks
permalink:        pretty

# Setup
title:            "Gianluca Pacchiella"
tagline:          'I code for food'
description:      'I code for food'
url:              'https://ktln2.org'
baseurl:          ''

author:
  name:           'Gianluca Pacchiella'
  url:            https://ktln2.org

paginate:         5
exclude:          ['extras/', 'LICENSE.md', 'README.md', 'CNAME',]
