markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'highlight'
  auto_ids: true
  hard_wrap: false # https://stackoverflow.com/questions/25418399/jekyll-converting-every-newline-as-line-break

# Permalinks
permalink:        pretty

# Setup
title:            "Gianluca Pacchiella"
tagline:          'I code for food'
description:      "Notes and experiments. Don't expect much quality :P"
url:              'https://ktln2.org'
baseurl:          ''

author:
  name:           'Gianluca Pacchiella'
  url:            https://ktln2.org

plugins:          [jekyll-paginate,rouge,jekyll_github_sample]
paginate:         5
exclude:          ['extras/', 'LICENSE.md', 'README.md', 'CNAME', 'provision', 'releases']
