# Dependencies
highligther:         pygments

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Gianluca Pacchiella"
tagline:          'I code for food'
description:      'I code for food'
url:              'https://ktln2.org'
baseurl:          ''

author:
  name:           'Gianluca Pacchiella'
  url:            https://ktln2.org

gems:             [jekyll-paginate,]
paginate:         5
exclude:          ['extras/', 'LICENSE.md', 'README.md', 'CNAME',]
